### ISSUE TITLE
Improve the readme page!

### ISSUE THREAD

**Issue by prakash-chakraborty** [Joonsang1994/Captain-India-Alexa#4]
The [readme](https://github.com/Joonsang1994/Captain-India-Alexa/blob/master/README.md) page is very basic. 

You can do the following improve the:
- Improve text. 
- Add Markdown styling.
- Add links to alexa tutorials
- Something interesting to make it spark!

You can go ahead and start making the changes. Commit and make a pull request.

If you are new, try contributing to [this](https://github.com/Joonsang1994/Hacktoberfest) first.

**Comment by preeti98** [comment]
May I please work on this issue?

**Comment by prakash-chakraborty** [comment]
Yes, please go ahead!

**Comment by AbidemiT** [comment]
I'm interested in this?

**Comment by AbidemiT** [comment]
Can i work on this?

**Comment by prakash-chakraborty** [comment]
> Can i work on this?

Yes please.
